[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
solc = '0.8.13'
viaIR = true

# See more config options https://github.com/gakonst/foundry/tree/master/config